project:
  type: website

website:
  title: "☂️ About me"
  
  page-footer:
       left: "-Haly-en-"
  page-navigation: true
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/Haly-en
      - icon: twitter
        href: https://twitter.com/HalyHalymary
format:
  html:
    smooth-scroll: true
    theme: Sketchy
    dark: darkly
    css: styles.css
    highlight-style: espresso #espresso, zenburn, eiffel
    footnotes-hover: true
    toc: true
    code-copy: true
    code-fold: true
    code-link: true
    code-line-numbers: true
execute:
  freeze: auto

